# _data/butterfly.yml
index_img: /img/pexels-charles-kettor-268979-831475.jpg     # 首页大图
default_top_img: /img/pexels-charles-kettor-268979-831475.jpg               # 默认内页顶部图
background: /img/pexels-pixabay-164634.jpg              # 全站背景

nav:
  logo: /img/pexels-harrisonhaines-2834653.jpg # 你的Logo
  display_title: true # 是否显示标题
  fixed: true        # 导航栏固定在顶部
  
# _data/butterfly.yml
aside:
  enable: true
  hide: false
  button: true # 侧边栏折叠按钮
  card_author:
    enable: true
    avatar: /img/pexels-giorgio-de-angelis-482403-1413412.jpg # 你的头像
    author: LiJi Do
    saying: 愿你眼里有星辰，心中有大海。
  card_announcement:
    enable: true
    content: 欢迎来到我的个人博客！
  card_recent_post:
    enable: true # 最近文章
  card_categories:
    enable: true # 分类卡片
    
comments:
  use:
    - Giscus
  lazyload: true
  
local_search:
  enable: true
  
font:
  global-font-size: 16px
  font-family: "'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif"
  
click_effects:
  enable: true
  type: firework # 可选: firework(烟花), heart(爱心)
  
